<h1 class="title">QException Class</h1>  <p>The QException class provides a base class for exceptions that can be transferred across threads. <a href="#details">More...</a></p>  <table class="alignedsummary"> <tr>
<td class="memItemLeft rightAlign topAlign"> Header:</td>
<td class="memItemRight bottomAlign"> <span class="preprocessor">#include &lt;QException&gt;</span> </td>
</tr>
<tr>
<td class="memItemLeft rightAlign topAlign"> CMake:</td>
<td class="memItemRight bottomAlign"> find_package(Qt6 COMPONENTS Core REQUIRED)  target_link_libraries(mytarget PRIVATE Qt6::Core)</td>
</tr>
<tr>
<td class="memItemLeft rightAlign topAlign"> qmake:</td>
<td class="memItemRight bottomAlign"> QT += core</td>
</tr>
<tr>
<td class="memItemLeft rightAlign topAlign"> Since:</td>
<td class="memItemRight bottomAlign"> Qt 5.0</td>
</tr>
<tr>
<td class="memItemLeft rightAlign topAlign"> Inherited By:</td>
<td class="memItemRight bottomAlign"> <p><a href="qunhandledexception.html">QUnhandledException</a></p> </td>
</tr>
</table> <ul> <li><a href="https://doc.qt.io/qt-6.2/qexception-members.html">List of all members, including inherited members</a></li> </ul> <h2 id="public-functions">Public Functions
</h2> <table class="alignedsummary"> <tr>
<td class="memItemLeft rightAlign topAlign"> virtual QException *</td>
<td class="memItemRight bottomAlign">
<b><a href="qexception.html#clone">clone</a></b>() const</td>
</tr> <tr>
<td class="memItemLeft rightAlign topAlign"> virtual void </td>
<td class="memItemRight bottomAlign">
<b><a href="qexception.html#raise">raise</a></b>() const</td>
</tr> </table>   <h2 id="details">Detailed Description
</h2> <p>Qt Concurrent supports throwing and catching exceptions across thread boundaries, provided that the exception inherits from QException and implements two helper functions:</p> <pre data-language="cpp">class MyException : public QException
{
public:
    void raise() const override { throw *this; }
    MyException *clone() const override { return new MyException(*this); }
};</pre> <p>QException subclasses must be thrown by value and caught by reference:</p> <pre data-language="cpp">try  {
    QtConcurrent::blockingMap(list, throwFunction); // throwFunction throws MyException
} catch (MyException &amp;e) {
    // handle exception
}</pre> <p>If you throw an exception that is not a subclass of QException, the <a href="qtconcurrent-index.html">Qt Concurrent</a> functions will throw a <a href="qunhandledexception.html">QUnhandledException</a> in the receiver thread.</p> <p>When using <a href="qfuture.html">QFuture</a>, transferred exceptions will be thrown when calling the following functions:</p> <ul> <li>
<a href="qfuture.html#waitForFinished">QFuture::waitForFinished</a>()</li> <li>
<a href="qfuture.html#result">QFuture::result</a>()</li> <li>
<a href="qfuture.html#resultAt">QFuture::resultAt</a>()</li> <li>
<a href="qfuture.html#results">QFuture::results</a>()</li> </ul>    <h2>Member Function Documentation</h2>  <h3 class="fn" id="clone">
<code>[virtual] </code><span class="type"><a href="qexception.html">QException</a></span> *QException::<span class="name">clone</span>() const
</h3> <p>In your <a href="qexception.html">QException</a> subclass, reimplement clone() like this:</p> <pre data-language="cpp">MyException *MyException::clone() const { return new MyException(*this); }</pre>   <h3 class="fn" id="raise">
<code>[virtual] </code><span class="type">void</span> QException::<span class="name">raise</span>() const
</h3> <p>In your <a href="qexception.html">QException</a> subclass, reimplement raise() like this:</p> <pre data-language="cpp">void MyException::raise() const { throw *this; }</pre><div class="_attribution">
  <p class="_attribution-p">
    &copy; The Qt Company Ltd<br>Licensed under the GNU Free Documentation License, Version 1.3.<br>
    <a href="https://doc.qt.io/qt-6.2/qexception.html" class="_attribution-link">https://doc.qt.io/qt-6.2/qexception.html</a>
  </p>
</div>
