<p class="_links"><a href="../../dart-async/dart-async-library.html" class="_links-link">dart:async</a></p> <h1>completeError method  </h1> <section class="multi-line-signature"> void completeError(<wbr><ol class="parameter-list">
<li>
<a href="../../dart-core/object-class.html">Object</a> error, </li> <li>[<a href="../../dart-core/stacktrace-class.html">StackTrace</a>? stackTrace]</li> </ol>) </wbr></section>  <p>Complete <a href="future.html">future</a> with an error.</p> <p>Calling <a href="complete.html">complete</a> or <a href="completeerror.html">completeError</a> must be done at most once.</p> <p>Completing a future with an error indicates that an exception was thrown while trying to produce a value.</p> <p>If <code>error</code> is a <code>Future</code>, the future itself is used as the error value. If you want to complete with the result of the future, you can use:</p> <pre class="language-dart" data-language="dart">thisCompleter.complete(theFuture)</pre> <p>or if you only want to handle an error from the future:</p> <pre class="language-dart" data-language="dart">theFuture.catchError(thisCompleter.completeError);</pre>   <h2 id="source">Implementation</h2> <pre class="language-dart" data-language="dart">void completeError(Object error, [StackTrace? stackTrace]);</pre><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2012 the Dart project authors<br>Licensed under the BSD 3-Clause "New" or "Revised" License.<br>
    <a href="https://api.dart.dev/stable/2.18.5/dart-async/Completer/completeError.html" class="_attribution-link">https://api.dart.dev/stable/2.18.5/dart-async/Completer/completeError.html</a>
  </p>
</div>
