<h1 id="label-Exception+Handling">
<a href="../exception.html"><code>Exception</code></a> Handling</h1> <p>Exceptions are rescued in a <code>begin</code>/<code>end</code> block:</p> <pre class="ruby" data-language="ruby">begin
  # code that might raise
rescue
  # handle exception
end
</pre> <p>If you are inside a method, you do not need to use <code>begin</code> or <code>end</code> unless you wish to limit the scope of rescued exceptions:</p> <pre class="ruby" data-language="ruby">def my_method
  # ...
rescue
  # ...
end
</pre> <p>The same is true for a <code>class</code>, <code>module</code>, and <code>block</code>:</p> <pre class="ruby" data-language="ruby">[0, 1, 2].map do |i|
  10 / i
rescue ZeroDivisionError
  nil
end
#=&gt; [nil, 10, 5]
</pre> <p>You can assign the exception to a local variable by using <code>=&gt; variable_name</code> at the end of the <code>rescue</code> line:</p> <pre class="ruby" data-language="ruby">begin
  # ...
rescue =&gt; exception
  warn exception.message
  raise # re-raise the current exception
end
</pre> <p>By default, <a href="../standarderror.html"><code>StandardError</code></a> and its subclasses are rescued. You can rescue a specific set of exception classes (and their subclasses) by listing them after <code>rescue</code>:</p> <pre class="ruby" data-language="ruby">begin
  # ...
rescue ArgumentError, NameError
  # handle ArgumentError or NameError
end
</pre> <p>You may rescue different types of exceptions in different ways:</p> <pre class="ruby" data-language="ruby">begin
  # ...
rescue ArgumentError
  # handle ArgumentError
rescue NameError
  # handle NameError
rescue
  # handle any StandardError
end
</pre> <p>The exception is matched to the rescue section starting at the top, and matches only once. If an <a href="../argumenterror.html"><code>ArgumentError</code></a> is raised in the begin section, it will not be handled in the <a href="../standarderror.html"><code>StandardError</code></a> section.</p> <p>You may retry rescued exceptions:</p> <pre class="ruby" data-language="ruby">begin
  # ...
rescue
  # do something that may change the result of the begin block
  retry
end
</pre> <p>Execution will resume at the start of the begin block, so be careful not to create an infinite loop.</p> <p>Inside a rescue block is the only valid location for <code>retry</code>, all other uses will raise a <a href="../syntaxerror.html"><code>SyntaxError</code></a>. If you wish to retry a block iteration use <code>redo</code>. See <a href="control_expressions_rdoc.html">Control Expressions</a> for details.</p> <p>To always run some code whether an exception was raised or not, use <code>ensure</code>:</p> <pre class="ruby" data-language="ruby">begin
  # ...
rescue
  # ...
ensure
  # this always runs BUT does not implicitly return the last evaluated statement.
end
</pre> <p>You may also run some code when an exception is not raised:</p> <pre class="ruby" data-language="ruby">begin
  # ...
rescue
  # ...
else
  # this runs only when no exception was raised AND return the last evaluated statement
ensure
  # this always runs.
  # It is evaluated after the evaluation of either the `rescue` or the `else` block.
  # It will not return implicitly.
end
</pre> <p>NB : Without explicit <code>return</code> in the <code>ensure</code> block, <code>begin</code>/<code>end</code> block will return the last evaluated statement before entering in the â€˜ensure` block.</p><div class="_attribution">
  <p class="_attribution-p">
    Ruby Core &copy; 1993&ndash;2024 Yukihiro Matsumoto<br>Licensed under the Ruby License.<br>Ruby Standard Library &copy; contributors<br>Licensed under their own licenses.<br>
    
  </p>
</div>
