<h1 tabindex="-1" dir="auto" id="error-handling">Error Handling</h1> <h2 tabindex="-1" dir="auto" id="try-catch">Try-Catch</h2> <p dir="auto">Using async functions means that you can try-catch <code>next</code>. This example adds a <code>.status</code> to all errors:</p> <pre data-language="js">app.use(async (ctx, next) =&gt; {
  try {
    await next();
  } catch (err) {
    err.status = err.statusCode || err.status || 500;
    throw err;
  }
});</pre> <h3 tabindex="-1" dir="auto" id="default-error-handler">Default Error Handler</h3> <p dir="auto">The default error handler is essentially a <code>try-catch</code> at the very beginning of the middleware chain. To use a different error handler, simply put another <code>try-catch</code> at the beginning of the middleware chain, and handle the error there. However, the default error handler is good enough for most use cases. It will use a status code of <code>err.status</code>, or by default 500. If <code>err.expose</code> is true, then <code>err.message</code> will be the reply. Otherwise, a message generated from the error code will be used (e.g. for the code 500 the message "Internal Server Error" will be used). All headers will be cleared from the request, but any headers in <code>err.headers</code> will then be set. You can use a <code>try-catch</code>, as specified above, to add a header to this list.</p> <p dir="auto">Here is an example of creating your own error handler:</p> <pre data-language="js">app.use(async (ctx, next) =&gt; {
  try {
    await next();
  } catch (err) {
    // will only respond with JSON
    ctx.status = err.statusCode || err.status || 500;
    ctx.body = {
      message: err.message
    };
  }
})</pre> <h2 tabindex="-1" dir="auto" id="the-error-event">The Error Event</h2> <p dir="auto">Error event listeners can be specified with <code>app.on('error')</code>. If no error listener is specified, a default error listener is used. Error listeners receive all errors that make their way back through the middleware chain, if an error is caught and not thrown again, it will not be passed to the error listener. If no error event listener is specified, then <code>app.onerror</code> will be used, which simply log the error unless <code>error.expose</code>is true or <code>app.silent</code> is true or <code>error.status</code> is 404.</p><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2020 Koa contributors<br>Licensed under the MIT License.<br>
    <a href="https://github.com/koajs/koa/tree/master/docs/error-handling.md" class="_attribution-link">https://github.com/koajs/koa/tree/master/docs/error-handling.md</a>
  </p>
</div>
