<h1 id="resumewithexception">resumeWithException</h1>
<div class="api-docs-breadcrumbs">
<a href="../../../../../index.html">kotlin-stdlib</a> / <a href="index.html">kotlin.coroutines</a> / <a href="resume-with-exception.html">resumeWithException</a>
</div> <div class="node-page-main" data-kotlin-version="1.3, 1.3, 1.3, 1.3" data-platform="Common, JVM, JS, Native">
<div data-kotlin-version="1.3, 1.3, 1.3, 1.3" data-platform="Common, JVM, JS, Native">
<b>Platform and version requirements:</b> JVM (1.3), JS (1.3), Native (1.3) </div>
<div data-kotlin-version="1.3, 1.3, 1.3, 1.3" data-platform="Common, JVM, JS, Native">
 <pre class="signature" data-language="kotlin">fun &lt;T&gt; Continuation&lt;T&gt;.resumeWithException(
    exception: Throwable)</pre> </div>
<div data-kotlin-version="1.3, 1.3, 1.3, 1.3" data-platform="Common, JVM, JS, Native"> <p>Resumes the execution of the corresponding coroutine so that the <a href="resume-with-exception.html#kotlin.coroutines$resumeWithException(kotlin.coroutines.Continuation((kotlin.coroutines.resumeWithException.T)),%20kotlin.Throwable)/exception">exception</a> is re-thrown right after the last suspension point.</p> </div>
</div><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2010&ndash;2023 JetBrains s.r.o. and Kotlin Programming Language contributors<br>Licensed under the Apache License, Version 2.0.<br>
    <a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.coroutines/resume-with-exception.html" class="_attribution-link">https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.coroutines/resume-with-exception.html</a>
  </p>
</div>
