  <div id="layout"> <div id="layout-content"><div id="exception.getprevious" class="refentry"> <div class="refnamediv"> <h1 class="refname">Exception::getPrevious</h1> <p class="verinfo">(PHP 5 &gt;= 5.3.0, PHP 7, PHP 8)</p>
<p class="refpurpose"><span class="refname">Exception::getPrevious</span> â€” <span class="dc-title">Returns previous Throwable</span></p> </div> <div class="refsect1 description" id="refsect1-exception.getprevious-description"> <h3 class="title">Description</h3> <pre class="methodsynopsis dc-description" data-language="php">final public Exception::getPrevious(): ?Throwable</pre> <p class="para rdfs-comment"> Returns previous <span class="classname"><a href="class.throwable.html" class="classname">Throwable</a></span> (which had been passed as the third parameter of <span class="methodname"><a href="exception.construct.html" class="methodname">Exception::__construct()</a></span>). </p> </div> <div class="refsect1 parameters" id="refsect1-exception.getprevious-parameters"> <h3 class="title">Parameters</h3> <p class="para">This function has no parameters.</p> </div> <div class="refsect1 returnvalues" id="refsect1-exception.getprevious-returnvalues"> <h3 class="title">Return Values</h3> <p class="para"> Returns the previous <span class="classname"><a href="class.throwable.html" class="classname">Throwable</a></span> if available or <strong><code>null</code></strong> otherwise. </p> </div> <div class="refsect1 examples" id="refsect1-exception.getprevious-examples"> <h3 class="title">Examples</h3> 
<div class="example" id="example-1112"> <p><strong>Example #1 <span class="methodname"><strong>Exception::getPrevious()</strong></span> example</strong></p> <div class="example-contents"><p> Looping over, and printing out, exception trace. </p></div> <div class="example-contents"> <pre class="phpcode" data-language="php">&lt;?php
class MyCustomException extends Exception {}

function doStuff() {
    try {
        throw new InvalidArgumentException("You are doing it wrong!", 112);
    } catch(Exception $e) {
        throw new MyCustomException("Something happened", 911, $e);
    }
}


try {
    doStuff();
} catch(Exception $e) {
    do {
        printf("%s:%d %s (%d) [%s]\n", $e-&gt;getFile(), $e-&gt;getLine(), $e-&gt;getMessage(), $e-&gt;getCode(), get_class($e));
    } while($e = $e-&gt;getPrevious());
}
?&gt;</pre> </div> <div class="example-contents"><p>The above example will output something similar to:</p></div> <div class="example-contents screen"> <div class="cdata"><pre>
/home/bjori/ex.php:8 Something happened (911) [MyCustomException]
/home/bjori/ex.php:6 You are doing it wrong! (112) [InvalidArgumentException]
</pre></div> </div> </div> </div> <div class="refsect1 seealso" id="refsect1-exception.getprevious-seealso"> <h3 class="title">See Also</h3> 
<ul class="simplelist"> <li class="member"><span class="methodname"><a href="throwable.getprevious.html" class="methodname" rel="rdfs-seeAlso">Throwable::getPrevious()</a> - Returns the previous Throwable</span></li> </ul> </div> </div></div>
</div><div class="_attribution">
  <p class="_attribution-p">
    &copy; 1997&ndash;2023 The PHP Documentation Group<br>Licensed under the Creative Commons Attribution License v3.0 or later.<br>
    <a href="https://www.php.net/manual/en/exception.getprevious.php" class="_attribution-link">https://www.php.net/manual/en/exception.getprevious.php</a>
  </p>
</div>
