  <div id="layout"> <div id="layout-content">
<div id="language.exceptions" class="chapter"> <h1 class="title">Exceptions</h1> <h2>Table of Contents</h2>
<ul class="chunklist chunklist_chapter"><li><a href="language.exceptions.extending.html">Extending Exceptions</a></li></ul> <p class="para"> PHP has an exception model similar to that of other programming languages. An exception can be <a href="language.exceptions.html" class="link"><code class="literal">throw</code></a>n, and caught ("<a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>ed") within PHP. Code may be surrounded in a <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> block, to facilitate the catching of potential exceptions. Each <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> must have at least one corresponding <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> or <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> block. </p> <p class="para"> If an exception is thrown and its current function scope has no <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> block, the exception will "bubble up" the call stack to the calling function until it finds a matching <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> block. All <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> blocks it encounters along the way will be executed. If the call stack is unwound all the way to the global scope without encountering a matching <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> block, the program will terminate with a fatal error unless a global exception handler has been set. </p> <p class="para"> The thrown object must be an <a href="language.operators.type.html" class="link"><code class="literal">instanceof</code></a> <span class="interfacename"><a href="class.throwable.html" class="interfacename">Throwable</a></span>. Trying to throw an object that is not will result in a PHP Fatal Error. </p> <p class="para"> As of PHP 8.0.0, the <a href="language.exceptions.html" class="link"><code class="literal">throw</code></a> keyword is an expression and may be used in any expression context. In prior versions it was a statement and was required to be on its own line. </p> <div id="language.exceptions.catch" class="sect1"> <h2 class="title"><code class="literal">catch</code></h2> <p class="para"> A <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> block defines how to respond to a thrown exception. A <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> block defines one or more types of exception or error it can handle, and optionally a variable to which to assign the exception. (The variable was required prior to PHP 8.0.0.) The first <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> block a thrown exception or error encounters that matches the type of the thrown object will handle the object. </p> <p class="para"> Multiple <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> blocks can be used to catch different classes of exceptions. Normal execution (when no exception is thrown within the <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> block) will continue after that last <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> block defined in sequence. Exceptions can be <a href="language.exceptions.html" class="link"><code class="literal">throw</code></a>n (or re-thrown) within a <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> block. If not, execution will continue after the <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> block that was triggered. </p> <p class="para"> When an exception is thrown, code following the statement will not be executed, and PHP will attempt to find the first matching <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> block. If an exception is not caught, a PHP Fatal Error will be issued with an "<code class="literal">Uncaught Exception ...</code>" message, unless a handler has been defined with <span class="function"><a href="function.set-exception-handler.html" class="function">set_exception_handler()</a></span>. </p> <p class="para"> As of PHP 7.1.0, a <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> block may specify multiple exceptions using the pipe (<code class="literal">|</code>) character. This is useful for when different exceptions from different class hierarchies are handled the same. </p> <p class="para"> As of PHP 8.0.0, the variable name for a caught exception is optional. If not specified, the <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> block will still execute but will not have access to the thrown object. </p> </div> <div id="language.exceptions.finally" class="sect1"> <h2 class="title"><code class="literal">finally</code></h2> <p class="para"> A <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> block may also be specified after or instead of <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> blocks. Code within the <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> block will always be executed after the <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> and <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> blocks, regardless of whether an exception has been thrown, and before normal execution resumes. </p> <p class="para"> One notable interaction is between the <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> block and a <a href="function.return.html" class="link"><code class="literal">return</code></a> statement. If a <a href="function.return.html" class="link"><code class="literal">return</code></a> statement is encountered inside either the <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> or the <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> blocks, the <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> block will still be executed. Moreover, the <a href="function.return.html" class="link"><code class="literal">return</code></a> statement is evaluated when encountered, but the result will be returned after the <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> block is executed. Additionally, if the <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> block also contains a <a href="function.return.html" class="link"><code class="literal">return</code></a> statement, the value from the <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> block is returned. </p> </div> <div id="language.exceptions.exception-handler" class="sect1"> <h2 class="title">Global exception handler</h2> <p class="para"> If an exception is allowed to bubble up to the global scope, it may be caught by a global exception handler if set. The <span class="function"><a href="function.set-exception-handler.html" class="function">set_exception_handler()</a></span> function can set a function that will be called in place of a <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> block if no other block is invoked. The effect is essentially the same as if the entire program were wrapped in a <a href="language.exceptions.html" class="link"><code class="literal">try</code></a>-<a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> block with that function as the <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>. </p> </div> <div id="language.exceptions.notes" class="sect1"> <h2 class="title">Notes</h2> <blockquote class="note">
<p><strong class="note">Note</strong>: </p>
<p class="para"> Internal PHP functions mainly use <a href="https://www.php.net/manual/en/errorfunc.configuration.php#ini.error-reporting" class="link">Error reporting</a>, only modern <a href="https://www.php.net/manual/en/language.oop5.php" class="link">Object-oriented</a> extensions use exceptions. However, errors can be easily translated to exceptions with <a href="class.errorexception.html" class="link">ErrorException</a>. This technique only works with non-fatal errors, however. </p> <div class="example" id="example-351"> <p><strong>Example #1 Converting error reporting to exceptions</strong></p> <div class="example-contents"> <pre class="phpcode" data-language="php">&lt;?php
function exceptions_error_handler($severity, $message, $filename, $lineno) {
    throw new ErrorException($message, 0, $severity, $filename, $lineno);
}

set_error_handler('exceptions_error_handler');
?&gt;</pre> </div> </div> </blockquote> <div class="tip">
<strong class="tip">Tip</strong> <p class="para"> The <a href="https://www.php.net/manual/en/intro.spl.php" class="link">Standard PHP Library (SPL)</a> provides a good number of <a href="https://www.php.net/manual/en/spl.exceptions.php" class="link">built-in exceptions</a>. </p> </div> </div> <div id="language.exceptions.examples" class="sect1"> <h2 class="title">Examples</h2> <div class="example" id="example-352"> <p><strong>Example #2 Throwing an Exception</strong></p> <div class="example-contents"> <pre class="phpcode" data-language="php">&lt;?php
function inverse($x) {
    if (!$x) {
        throw new Exception('Division by zero.');
    }
    return 1/$x;
}

try {
    echo inverse(5) . "\n";
    echo inverse(0) . "\n";
} catch (Exception $e) {
    echo 'Caught exception: ',  $e-&gt;getMessage(), "\n";
}

// Continue execution
echo "Hello World\n";
?&gt;</pre> </div> <div class="example-contents"><p>The above example will output:</p></div> <div class="example-contents screen"> <div class="cdata"><pre>
0.2
Caught exception: Division by zero.
Hello World
</pre></div> </div> </div> <div class="example" id="example-353"> <p><strong>Example #3 Exception handling with a <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> block</strong></p> <div class="example-contents"> <pre class="phpcode" data-language="php">&lt;?php
function inverse($x) {
    if (!$x) {
        throw new Exception('Division by zero.');
    }
    return 1/$x;
}

try {
    echo inverse(5) . "\n";
} catch (Exception $e) {
    echo 'Caught exception: ',  $e-&gt;getMessage(), "\n";
} finally {
    echo "First finally.\n";
}

try {
    echo inverse(0) . "\n";
} catch (Exception $e) {
    echo 'Caught exception: ',  $e-&gt;getMessage(), "\n";
} finally {
    echo "Second finally.\n";
}

// Continue execution
echo "Hello World\n";
?&gt;</pre> </div> <div class="example-contents"><p>The above example will output:</p></div> <div class="example-contents screen"> <div class="cdata"><pre>
0.2
First finally.
Caught exception: Division by zero.
Second finally.
Hello World
</pre></div> </div> </div> <div class="example" id="example-354"> <p><strong>Example #4 Interaction between the <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> block and <a href="function.return.html" class="link"><code class="literal">return</code></a></strong></p> <div class="example-contents"> <pre class="phpcode" data-language="php">&lt;?php

function test() {
    try {
        throw new Exception('foo');
    } catch (Exception $e) {
        return 'catch';
    } finally {
        return 'finally';
    }
}

echo test();
?&gt;</pre> </div> <div class="example-contents"><p>The above example will output:</p></div> <div class="example-contents screen"> <div class="cdata"><pre>
finally
</pre></div> </div> </div> <div class="example" id="example-355"> <p><strong>Example #5 Nested Exception</strong></p> <div class="example-contents"> <pre class="phpcode" data-language="php">&lt;?php

class MyException extends Exception { }

class Test {
    public function testing() {
        try {
            try {
                throw new MyException('foo!');
            } catch (MyException $e) {
                // rethrow it
                throw $e;
            }
        } catch (Exception $e) {
            var_dump($e-&gt;getMessage());
        }
    }
}

$foo = new Test;
$foo-&gt;testing();

?&gt;</pre> </div> <div class="example-contents"><p>The above example will output:</p></div> <div class="example-contents screen"> <div class="cdata"><pre>
string(4) "foo!"
</pre></div> </div> </div> <div class="example" id="example-356"> <p><strong>Example #6 Multi catch exception handling</strong></p> <div class="example-contents"> <pre class="phpcode" data-language="php">&lt;?php

class MyException extends Exception { }

class MyOtherException extends Exception { }

class Test {
    public function testing() {
        try {
            throw new MyException();
        } catch (MyException | MyOtherException $e) {
            var_dump(get_class($e));
        }
    }
}

$foo = new Test;
$foo-&gt;testing();

?&gt;</pre> </div> <div class="example-contents"><p>The above example will output:</p></div> <div class="example-contents screen"> <div class="cdata"><pre>
string(11) "MyException"
</pre></div> </div> </div> <div class="example" id="example-357"> <p><strong>Example #7 Omitting the caught variable</strong></p> <div class="example-contents"><p>Only permitted in PHP 8.0.0 and later.</p></div> <div class="example-contents"> <pre class="phpcode" data-language="php">&lt;?php

class SpecificException extends Exception {}

function test() {
    throw new SpecificException('Oopsie');
}

try {
    test();
} catch (SpecificException) {
    print "A SpecificException was thrown, but we don't care about the details.";
}
?&gt;</pre> </div> </div> <div class="example" id="example-358"> <p><strong>Example #8 Throw as an expression</strong></p> <div class="example-contents"><p>Only permitted in PHP 8.0.0 and later.</p></div> <div class="example-contents"> <pre class="phpcode" data-language="php">&lt;?php

function test() {
    do_something_risky() or throw new Exception('It did not work');
}

try {
    test();
} catch (Exception $e) {
    print $e-&gt;getMessage();
}
?&gt;</pre> </div> </div> </div> </div> </div>
</div><div class="_attribution">
  <p class="_attribution-p">
    &copy; 1997&ndash;2024 The PHP Documentation Group<br>Licensed under the Creative Commons Attribution License v3.0 or later.<br>
    <a href="https://www.php.net/manual/en/language.exceptions.php" class="_attribution-link">https://www.php.net/manual/en/language.exceptions.php</a>
  </p>
</div>
