<h1>pandas.errors.IndexingError</h1> <dl class="py exception"> <dt class="sig sig-object py" id="pandas.errors.IndexingError"> <em class="property"><span class="pre">exception</span></em><span class="sig-prename descclassname"><span class="pre">pandas.errors.</span></span><span class="sig-name descname"><span class="pre">IndexingError</span></span><a class="reference external" href="https://github.com/pandas-dev/pandas/blob/v2.2.2/pandas/errors/__init__.py#L598-L616"><span class="viewcode-link"><span class="pre">[source]</span></span></a>
</dt> <dd>
<p>Exception is raised when trying to index and there is a mismatch in dimensions.</p> <p class="rubric">Examples</p> <div class="doctest highlight-default notranslate">
<div class="highlight"><pre data-language="python">&gt;&gt;&gt; df = pd.DataFrame({'A': [1, 1, 1]})
&gt;&gt;&gt; df.loc[..., ..., 'A'] 
... # IndexingError: indexer may only contain one '...' entry
&gt;&gt;&gt; df = pd.DataFrame({'A': [1, 1, 1]})
&gt;&gt;&gt; df.loc[1, ..., ...] 
... # IndexingError: Too many indexers
&gt;&gt;&gt; df[pd.Series([True], dtype=bool)] 
... # IndexingError: Unalignable boolean Series provided as indexer...
&gt;&gt;&gt; s = pd.Series(range(2),
...               index = pd.MultiIndex.from_product([["a", "b"], ["c"]]))
&gt;&gt;&gt; s.loc["a", "c", "d"] 
... # IndexingError: Too many indexers
</pre></div> </div> </dd>
</dl><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2008&ndash;2022, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team<br>Licensed under the 3-clause BSD License.<br>
    <a href="https://pandas.pydata.org/pandas-docs/version/2.2.2/reference/api/pandas.errors.IndexingError.html" class="_attribution-link">https://pandas.pydata.org/pandas-docs/version/2.2.2/reference/api/pandas.errors.IndexingError.html</a>
  </p>
</div>
