<h1>pandas.errors.AttributeConflictWarning</h1> <dl class="py exception"> <dt class="sig sig-object py" id="pandas.errors.AttributeConflictWarning"> <em class="property"><span class="pre">exception</span></em><span class="sig-prename descclassname"><span class="pre">pandas.errors.</span></span><span class="sig-name descname"><span class="pre">AttributeConflictWarning</span></span><a class="reference external" href="https://github.com/pandas-dev/pandas/blob/v2.2.2/pandas/errors/__init__.py#L693-L711"><span class="viewcode-link"><span class="pre">[source]</span></span></a>
</dt> <dd>
<p>Warning raised when index attributes conflict when using HDFStore.</p> <p>Occurs when attempting to append an index with a different name than the existing index on an HDFStore or attempting to append an index with a different frequency than the existing index on an HDFStore.</p> <p class="rubric">Examples</p> <div class="doctest highlight-default notranslate">
<div class="highlight"><pre data-language="python">&gt;&gt;&gt; idx1 = pd.Index(['a', 'b'], name='name1')
&gt;&gt;&gt; df1 = pd.DataFrame([[1, 2], [3, 4]], index=idx1)
&gt;&gt;&gt; df1.to_hdf('file', 'data', 'w', append=True)  
&gt;&gt;&gt; idx2 = pd.Index(['c', 'd'], name='name2')
&gt;&gt;&gt; df2 = pd.DataFrame([[5, 6], [7, 8]], index=idx2)
&gt;&gt;&gt; df2.to_hdf('file', 'data', 'a', append=True)  
AttributeConflictWarning: the [index_name] attribute of the existing index is
[name1] which conflicts with the new [name2]...
</pre></div> </div> </dd>
</dl><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2008&ndash;2022, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team<br>Licensed under the 3-clause BSD License.<br>
    <a href="https://pandas.pydata.org/pandas-docs/version/2.2.2/reference/api/pandas.errors.AttributeConflictWarning.html" class="_attribution-link">https://pandas.pydata.org/pandas-docs/version/2.2.2/reference/api/pandas.errors.AttributeConflictWarning.html</a>
  </p>
</div>
