    <h1 id="firstHeading" class="firstHeading">std::rethrow_exception</h1>            <table class="t-dcl-begin"> <tr class="t-dsc-header"> <th> Defined in header <code><a href="../header/exception.html" title="cpp/header/exception">&lt;exception&gt;</a></code> </th> <th> </th> <th> </th> </tr> <tr class="t-dcl t-since-cxx11"> <td> <pre data-language="cpp">[[noreturn]] void rethrow_exception( std::exception_ptr p );</pre>
</td> <td class="t-dcl-nopad"> </td> <td> <span class="t-mark-rev t-since-cxx11">(since C++11)</span> </td> </tr>  </table> <p>Throws the previously captured exception object referred-to by the exception pointer <code>p</code>, or a copy of that object.</p>
<p>It is unspecified whether a copy is made. If a copy is made, the storage for it is allocated in an unspecified way.</p>
<p>The behavior is undefined if <code>p</code> is null.</p>
<h3 id="Parameters"> Parameters</h3> <table class="t-par-begin"> <tr class="t-par"> <td> p </td> <td> - </td> <td> non-null <code><a href="exception_ptr.html" title="cpp/error/exception ptr">std::exception_ptr</a></code> </td>
</tr>
</table> <h3 id="Return_value"> Return value</h3> <p>(none)</p>
<h3 id="Exceptions"> Exceptions</h3> <p>The exception object referred-to by <code>p</code> if no copy is made.</p>
<p>Otherwise, a copy of such exception object if the implementation successfully copied the exception object.</p>
<p>Otherwise, <code><a href="../memory/new/bad_alloc.html" title="cpp/memory/new/bad alloc">std::bad_alloc</a></code> or the exception thrown when copying the exception object, if allocation or copying fails, respectively.</p>
<h3 id="Notes"> Notes</h3> <p>Before <a rel="nofollow" class="external text" href="https://wg21.link/P1675R2">P1675R2</a>, <code>rethrow_exception</code> was not allowed to copy the exception object, which is unimplementable on some platforms where exception objects are allocated on the stack.</p>
<h3 id="Example"> Example</h3> 
<div class="t-example"> <div class="cpp source-cpp"><pre data-language="cpp">#include &lt;exception&gt;
#include &lt;iostream&gt;
#include &lt;stdexcept&gt;
#include &lt;string&gt;
 
void handle_eptr(std::exception_ptr eptr) // passing by value is ok
{
    try
    {
        if (eptr)
            std::rethrow_exception(eptr);
    }
    catch(const std::exception&amp; e)
    {
        std::cout &lt;&lt; "Caught exception: '" &lt;&lt; e.what() &lt;&lt; "'\n";
    }
}
 
int main()
{
    std::exception_ptr eptr;
 
    try
    {
        std::string().at(1); // this generates a std::out_of_range
    }
    catch(...)
    {
        eptr = std::current_exception(); // capture
    }
 
    handle_eptr(eptr);
 
} // destructor for std::out_of_range called here, when the eptr is destructed</pre></div> <p>Possible output:</p>
<div class="text source-text"><pre data-language="c">Caught exception: 'basic_string::at: __n (which is 1) &gt;= this-&gt;size() (which is 0)'</pre></div> </div> <h3 id="See_also"> See also</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="exception_ptr.html" title="cpp/error/exception ptr"> <span class="t-lines"><span>exception_ptr</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> shared pointer type for handling exception objects <br> <span class="t-mark">(typedef)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="current_exception.html" title="cpp/error/current exception"> <span class="t-lines"><span>current_exception</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> captures the current exception in a <code><a href="exception_ptr.html" title="cpp/error/exception ptr">std::exception_ptr</a></code> <br> <span class="t-mark">(function)</span>  </td>
</tr> </table>           <div class="_attribution">
  <p class="_attribution-p">
    &copy; cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="https://en.cppreference.com/w/cpp/error/rethrow_exception" class="_attribution-link">https://en.cppreference.com/w/cpp/error/rethrow_exception</a>
  </p>
</div>
