<p class="_links"><a href="../../dart-async/dart-async-library.html" class="_links-link">dart:async</a></p> <h1>catchError method  </h1> <section class="multi-line-signature"> <a href="../future-class.html">Future</a>&lt;<wbr>T&gt;</wbr> catchError(<wbr><ol class="parameter-list">
<li>
<a href="../../dart-core/function-class.html">Function</a> onError, </li> <li>{<a href="../../dart-core/bool-class.html">bool</a> test(<ol class="parameter-list">
<li>
<a href="../../dart-core/object-class.html">Object</a> error</li> </ol> )?}</li> </ol>) </wbr></section>  <p>Handles errors emitted by this <a href="../future-class.html">Future</a>.</p> <p>This is the asynchronous equivalent of a "catch" block.</p> <p>Returns a new <a href="../future-class.html">Future</a> that will be completed with either the result of this future or the result of calling the <code>onError</code> callback.</p> <p>If this future completes with a value, the returned future completes with the same value.</p> <p>If this future completes with an error, then <code>test</code> is first called with the error value.</p> <p>If <code>test</code> returns false, the exception is not handled by this <code>catchError</code>, and the returned future completes with the same error and stack trace as this future.</p> <p>If <code>test</code> returns <code>true</code>, <code>onError</code> is called with the error and possibly stack trace, and the returned future is completed with the result of this call in exactly the same way as for <a href="then.html">then</a>'s <code>onError</code>.</p> <p>If <code>test</code> is omitted, it defaults to a function that always returns true. The <code>test</code> function should not throw, but if it does, it is handled as if the <code>onError</code> function had thrown.</p> <p>Note that futures don't delay reporting of errors until listeners are added. If the first <code>catchError</code> (or <code>then</code>) call happens after this future has completed with an error then the error is reported as unhandled error. See the description on <a href="../future-class.html">Future</a>.</p> <p>Example:</p> <pre class="language-dart" data-language="dart">Future.delayed(
  const Duration(seconds: 1),
  () =&gt; throw 401,
).then((value) {
  throw 'Unreachable';
}).catchError((err) {
  print('Error: $err'); // Prints 401.
}, test: (error) {
  return error is int &amp;&amp; error &gt;= 400;
});</pre>   <h2 id="source">Implementation</h2> <pre class="language-dart" data-language="dart">// The `Function` below stands for one of two types:
// - (dynamic) -&gt; FutureOr&lt;T&gt;
// - (dynamic, StackTrace) -&gt; FutureOr&lt;T&gt;
// Given that there is a `test` function that is usually used to do an
// `is` check, we should also expect functions that take a specific argument.
Future&lt;T&gt; catchError(Function onError, {bool test(Object error)?});</pre><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2012 the Dart project authors<br>Licensed under the BSD 3-Clause "New" or "Revised" License.<br>
    <a href="https://api.dart.dev/stable/2.18.5/dart-async/Future/catchError.html" class="_attribution-link">https://api.dart.dev/stable/2.18.5/dart-async/Future/catchError.html</a>
  </p>
</div>
